-- MySQL Script generated by MySQL Workbench
-- Sun Jul 20 15:53:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_php1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_php1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_php1` DEFAULT CHARACTER SET utf8 ;
USE `app_php1` ;

-- -----------------------------------------------------
-- Table `app_php1`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_php1`.`Persona` ;

CREATE TABLE IF NOT EXISTS `app_php1`.`Persona` (
  `idPersona` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPersona_UNIQUE` ON `app_php1`.`Persona` (`idPersona` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
